threads-api/src/threads-types.ts
threads-web-ui/next.config.js
threads-web-ui/src/components/GlobalStyle.tsx
threads-web-ui/src/pages/[username].tsx
threads-web-ui/src/pages/_document.tsx

[api][web-ui] Show list of User Threads in Web UI

---

.vscode/settings.json
threads-api/__test__/getUserIDfromUsername.test.ts
threads-api/src/threads-api.ts

[api] Update `fbLSDToken` on each `getUserIDfromUsername` call

---

threads-api/src/threads-api.ts

[api] Make `httpAgent` to be injected via `ThreadsAPIOptions`

---

threads-api/src/threads-api.ts

Add proxy options

---

README.md
threads-api/bin/cli.js
threads-api/package.json
threads-api/src/cli.ts
threads-api/src/index.ts
yarn.lock

Follow-up for @Digital39999's work in #37

[api] Make CLI work with npx

---

README.md
threads-api/__test__/getPostIDfromThreadID.test.ts
threads-api/src/threads-api.ts

```ts
const postID = await threadsAPI.getPostIDfromThreadID('CuW6-7KyXme'); // 3140957200974444958
```

[api] Implement `ThreadsAPI.getPostIDfromThreadID`

---

threads-api/src/threads-api.ts

Use like the following:
```
import { ThreadsAPI } from 'threads-api';
const main = async () => {
const threadsAPI = new ThreadsAPI({
username: 'jamel.hammoud',
password: 'password',
});
await threadsAPI.publish('Hello World');
};
main();
```

Add publishing ability to the Threads API

---

README.md
threads-api/src/cli.ts
threads-api/src/threads-api.ts

- Follow-up to @JamelHammoud's work in #43

[api][docs] Add Usage for Writing Threads in README.md, Fix naming

---

README.md

I made a small project to share your Threads profile with people.
Currently it only shows your profile picture, name, biography and links alongside a QR Code to your profile, but I intend on adding the ability to put multiple other socials, pin your favorite thread, etc.
repo: https://github.com/yssf-io/threads-card
demo: https://threads-card.vercel.app/
Feel free to format the README how you want

Add threads-card project

---

threads-web-ui/package.json
threads-web-ui/src/components/GlobalStyle.tsx
threads-web-ui/src/pages/[username].tsx
threads-web-ui/src/pages/index.tsx
threads-web-ui/tailwind.config.js
yarn.lock

- https://github.com/junhoyeo/react-threads

[web-ui] Use `<Thread />` component from `react-threads`

---

.vscode/settings.json
README.md
fetch-dynamic-data/index.deno.ts
threads-api/src/dynamic-data.ts
threads-api/src/threads-api.ts

This pull request introduces several improvements and fixes to enhance the functionality and user experience of the library:
1. Dynamically fetch data on compile time: This feature enables the fetching of data during compile time, such as app versions, to formulate user agents more accurately. This helps reduce the likelihood of detection and improves overall accuracy.
2. Support for defining custom devices: Currently, the project supports custom devices specifically for Android devices. This enhancement allows users to define their own custom devices, expanding the flexibility the library.
3. Deno README installation fix: The Deno README installation instructions have been corrected to ensure accurate installation and seamless integration with Deno.

[Enhancement/Feature/Bug Fix] Dynamically fetch data, custom devices support, and Deno README installation fix

---

README.md

Added Strings : Frontend for Threads using threads-api

---

threads-api/__test__/getToken.test.ts
threads-api/__test__/publish.test.ts
threads-api/__test__/publishWithImage.test.ts
threads-api/package.json
threads-api/src/constants.ts
threads-api/src/threads-api.ts
yarn.lock

- new feature(publish with image) : but didn't upload image.
- add test code(publish, publish with image, get token)

[api] Publishing Thread with image

---

threads-api/__test__/getToken.test.ts
threads-api/__test__/publish.test.ts
threads-api/__test__/publishWithImage.test.ts
threads-api/__test__/utils/constants.ts
threads-api/__test__/utils/describeIf.ts

Related with #52 https://github.com/junhoyeo/threads-api/pull/52#issuecomment-1627687223 #62 #66
cc @Mineru98

[api] test: skip auth-required tests if credentials not provided

---

threads-api/src/constants.ts
threads-api/src/threads-api.ts

Closes #70. Problem was with fetching image data.

[api] Make `theadsAPI.uploadImage` to use correct binary file

---

threads-api/__test__/publish.test.ts
threads-api/__test__/publishWithImage.test.ts
threads-api/src/constants.ts
threads-api/src/threads-api.ts

[api] Manage `token` state inside `ThreadsAPI`

---

threads-api/__test__/publish.test.ts
threads-api/__test__/publishWithImage.test.ts
threads-api/src/threads-api.ts

[api] Implement new `publish` with options and backwards compatibility

---

threads-api/__test__/publish.test.ts
threads-api/__test__/publishWithImage.test.ts
threads-api/src/threads-api.ts

[api] Implement `link` and `replyPostId` option of `publish`

---

threads-api/src/constants.ts
threads-api/src/threads-api.ts

Closes #88 
You can now delete posts! I also updated the `publish` function to return the published post `ID`.
You can use it like this:
```
const threadsAPI = new ThreadsAPI({
username: 'jamel.hammoud',
password: 'PASSWORD,
});
const postId = await threadsAPI.publish('This will delete in 2 seconds');
setTimeout(() => {
threadsAPI.delete(postId);
}, 2000);

Post Deleting

---

threads-api/README.md

Hi @junhoyeo.
First off, I just wanted to thank you so much for your continuous and excellent work on the Threads.net unofficial API. I am truly amazed with the speed with which you are pushing out incredibly useful updates.
I have just created two projects using your API and would love to be featured alongside the others on the page. 
Please do look into my request. I would be happy to provide any information that you may need.
Little bit about the projects:
<p align="center">
</p>
The Fortune Cookie Bot is one of the projects within the Threads-Projects repository. The motivation behind this project is to provide Threads.net users with valuable insights and a daily dose of wisdom. The bot leverages the [Advice Slip API](https://api.adviceslip.com/advice) to fetch interesting advice and …

Updated README.md to add my project details

---

threads-api/src/threads-api.ts

[api] Import module `fs` right before it's used

---

threads-api/README.md
threads-api/package.json
threads-api/src/constants.ts
threads-api/src/threads-api.ts

[api][docs] Fix nit & update docs for `delete` method

---

threads-api/src/cli.ts

Created a timeout, createCommand function reduce code repetition and I dynamically generate aliases based on the first three characters of each word

Refactoring code for improved readability and optimization

---

threads-api/src/cli.ts

Reverts junhoyeo/threads-api#119

Revert "Refactoring code for improved readability and optimization"

---

threads-api/src/threads-api.ts

[api] Fix length check in `_destructureFromUserIDQuerier`

---

threads-api/src/threads-api.ts

Fixes https://github.com/junhoyeo/threads-api/issues/132

Do not require username and pass if token is provided

---

threads-api/src/threads-api.ts

PR for https://github.com/junhoyeo/threads-api/issues/129

Max retries

---

.imgbotconfig
threads-api/README.md

This pull request introduces the [`thread-year-prog-bot`](https://github.com/SethuSenthil/thread-year-prog-bot) project, an open-source project that showcases the implementation of a practical Instagram Threads bot using the threads-API. The project serves as both an educational resource and a reference for developers interested in building similar applications and to also have an existential crisis!
Additionally, this pull request includes an automatic formatting update to the `.imgbotconfig` file.
Changes:
- Added `thread-year-prog-bot` project, demonstrating a real-world Instagram Threads bot example using the threads-API.
- Auto-formatted the `.imgbotconfig` file for improved code consistency.

Add `thread-year-prog-bot` to projects and format .imgbotconfig

---

threads-api/src/threads-api.ts

thinking about naming, just settled with `unrepost` cuz `unretweet` was pretty common & https://github.com/threadsjs/threads.js also adopted it too

[api] Implement repost/unrepost

---

threads-api/src/threads-api.ts

Sorry I was late having breakfast (or is it supper?!)

[api] Add `quotedPostID` option to `publish` method

---

threads-api/src/constants.ts
threads-api/src/threads-api.ts

[api] Fix `deviceID` check in constructor

---

threads-api/README.md
threads-api/__test__/getUserFollows.test.ts
threads-api/src/threads-api.ts

[api] Rename: `getUserFollowing` -> `getUserFollowings`

---

threads-api/README.md

docs: Update README.md

---

threads-api/src/threads-api.ts

add params httpAgent/httpsAgent at login for proxy and add sample for getToken using proxy

add httpAgent/httpsAgent at login for proxy

---

threads-api/src/threads-api.ts

add httpAgent/httpsAgent at syncLoginExperiments, forgot last pull.

add httpAgent/httpsAgent at syncLoginExperiments for proxy auth

---

threads-api/__test__/getTokenWithProxy.test.ts

Update and rename getToken.test.ts to getTokenWithProxy.test.ts

---

threads-web-ui/data/apps.ts

Btw, I'm fixing the information regarding "String" application.

Add my app :smiley:

---

threads-api/src/threads-api.ts

api: Remove unused logs

---

threads-api/README.md
threads-api/src/threads-api.ts

- Document methods added in #189

api, docs: Refactor API, Update README.md with new methods

---

threads-api/src/threads-api.ts

The `device` property was not using `DEFAULT_DEVICE` (because of the line below)
https://github.com/junhoyeo/threads-api/blob/4e7049aa71ed2996d62b62d338f4d085d7d6a522/threads-api/src/threads-api.ts#L356
I made a few other readability improvements:
- I cleaned up the constructor by grouping property type declarations and property assignments the same way they're grouped in `ThreadsAPI.Options` type.
- I moved all property initialization into the constructor.
- I moved the deviceID warning into `generateDeviceID`.

fix: ensure `this.device` is defined

---

threads-web-ui/data/apps.ts

Added my own threads bot based on gpt.Please add it to app list

Add my bot to app registry
