junhoyeo/threads-api

threads-api/src/threads-api.ts
Fixes #31 by replacing Threads with Instagram to get the `userID` from `username`.
=> [api] replaced Threads by Instagram in getUserIDByUsername

threads-api/src/threads-api.ts
The current implementation hard-codes the timezone offset for the PST timezone. This commit introduces changes to dynamically calculate the timezone offset based on the user's timezone. By doing so, we reduce the risk of account bans and detection by adapting to the user's specific time zone. This improves the overall reliability and robustness of the system.
Currently, this mainly affects the ".publish" method to create new threads
=> Dynamically calculate timezone offset based on user's timezone

threads-api/src/threads-api.ts
Why use external agent type when you can use axios'? Currently prevents use of libraries like `https-proxy-agent`.
=> [fix] Agent compatibility issues

threads-api/src/threads-api.ts
Adding a way to use http(s)Agent as well while using Axios.
Might be useful when using proxies to call the underlying APIs.
=> Add option to pass in httpsAgent as an option for calling Axios

README.md, threads-api/src/threads-api.ts
=> [api][docs] Rename: `replyPostId` -> `parentPostID`, Update README for new `publish` API

threads-api/package.json, yarn.lock
Adding simple package [rimraf](https://npmjs.com/package/rimraf) to use with scripts so `yarn build` will work cross-platform (windows)
=> Use rimraf for cross environment dev

threads-api/src/threads-api.ts
This should help with AWS blocking. We basically first use the Threads URL, and then the IG if that fails.
It looks like IG is more difficult from AWS, but Threads works, and if Threads profiles go down (like last time), we have a backup with IG.
But I think we should still be looking at other ways to get the `userID`.
PS: it works on my EC2 but still spotty
=> [api] added instagram as backup for getting userID

threads-api/package.json, threads-api/src/threads-api.ts
Use `mrmime` instead of `mime-types` since it's 13% the size for same feature set.
https://bundlephobia.com/package/mrmime@1.0.1
https://bundlephobia.com/package/mime-types@2.1.35
=> feat: use mrmime instead of mime-types

threads-api/src/threads-api.ts
Allows the following API call:
```ts
threadsAPI.uploadImage({ name: 'image.png', data: Buffer.from(…) })
```
The `name` is used to determine the MIME type. You can simply do `".png"` or even `"png"` and it still works the same.
=> feat: allow inline image upload

threads-web-ui/package.json
- NextJS version mismatch in the root folder of `threads-web-ui` and in the dependency of `react-threads`
- Apparently `react-threads` requires `next@13.4.9` version, but in the [package.json](https://github.com/junhoyeo/threads-api/blob/main/threads-web-ui/package.json) of the `threads-web-ui` only `next@13.4.4` is mentioned.
- Altered it to `"next": "^13.4.4"` in the [package.json](https://github.com/junhoyeo/threads-api/blob/main/threads-web-ui/package.json) file.
=> FIX: NextJS version mismatch in the dependency tree

threads-api/src/threads-api.ts, yarn.lock
This pull request aims to enhance the handling of the `accept-language` header in the codebase. The current implementation hardcodes the language to `ko` (Korean), which can potentially cause issues in the future and make the library more detectable. To address this, I have made the following changes:
1. Utilized the cross-platform `Intl` namespace [learn more here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl), which is built into the Node.js, Deno, and Browser runtimes, to retrieve the preferred language setting from the device or server where the code is running.
2. Exposed the language setting as a configurable option, allowing users to manually set the desired language if needed.
These changes improve the flexibility and future-proofing of the …
=> [Fix / Enhancement] Improve `accept-language` header handling

threads-api/src/threads-api.ts
This PR implements the calls made within the app to populate a user's threads and replies.
The big thing here is that it supports **PAGINATION** using instagram's `max_id` query param (renamed to `cursor`)
Please rip this PR apart if there is a better way you'd prefer for this type of implementation! ❤️
=> User Feed Queries for Logged in Users - Pagination!

package.json, threads-api/src/threads-api.ts, yarn.lock
This pull request adds built-in support for reading `.env` configuration files so users can safely pass in their usernames, passwords, and device identifiers without hardcoding them.
The order of precedence is:
- Values passed in the constructor will override `.env`
- `.env` will override defaults
Out of the box, the following `.env` values are supported:
- `THREAD_USERNAME` - Thread/Instagram username 
- `THREAD_PASSWORD` - Thread/Instagram password
- `THREAD_DEVICE_ID` - Device ID for requests
=> 🔏 Add support for .env config out of the box

threads-api/README.md
The details block ending tag had been placed incorrectly, such that none of the README contents were showing correctly.
=> Updated README.md to fix issue with details block

threads-api/README.md, threads-api/__test__/getPostIDfromThreadID.test.ts, threads-api/__test__/getPostIDfromURL.test.ts, threads-api/__test__/interaction-like-and-unlike.test.ts, threads-api/src/threads-api.ts
- Fixes #149 (https://github.com/junhoyeo/threads-api/issues/149#issuecomment-1636198187)
- https://github.com/junhoyeo/threads-py/pull/27
- Note: we need to use `bigint` to handle arbitrary large integers
=> [api] Statically get Post ID with base64 encoding

threads-api/src/threads-api.ts
The post ID returned by `publish` includes the user ID at the end (e.g. `3148420376389470708_60654468808`), which is fine, but the `publish` endpoint expects `reply_id` and `quoted_post_id` to not have the user ID part (e.g. `3148420376389470708` only).
Fixes https://github.com/junhoyeo/threads-api/issues/149#issue-1803468082
=> fix: strip user ID from parentPostID and quotedPostID

threads-web-ui/app/page.tsx
| Before | After |
|:---:|:---:|
| <img width="313" alt="Screenshot 2023-07-18 at 4 26 36 AM" src="https://github.com/junhoyeo/threads-api/assets/32605822/730f7e80-74e7-4f3d-8798-b271873e5ebe"> | <img width="314" alt="Screenshot 2023-07-18 at 4 26 23 AM" src="https://github.com/junhoyeo/threads-api/assets/32605822/66284f3f-02b5-410b-96ed-d1677ec148d7"> |
=> [web-ui] Workaround for overflow: hidden + border-radius bug in Safari

threads-api/src/threads-api.ts
The "types/utils" specifier cannot be resolved when this package is installed from NPM, since it is provided by tsconfig baseUrl option.
=> fix: broken type import

threads-api/src/threads-api.ts
The PR add new methods for some that do not require authentication and fixes the issues of not retrieving data. #188  and #175 
**Added**
```typescript
_getUnAuthenticatedHeaders
``` 
**Reason**
This was added because some methods that do not require the header `Authorization` were failing because of it.
**Added**
```
_getDefaultUserDataHeaders
``` 
**Reason**
Simply to pass the `getUnAuthenticatedHeaders` to methods that do not require authentication like `getUserProfile` `getThreads` `getThreadsLikers` 
**Added**
```
_getDefaultRepliesHeaders  | _requestRepliesQuery 
```
**Reason**
The motive to add these two were because the referer header to the `threads.net/api/graphql` endpoint includes the `/replies` path when is not logged in.
**Note** : 
>  getProfilePage and …
=> fix: methods failing because of token or headers

threads-api/src/threads-api.ts
changed the name of _getProfilePage to a more clear and  direct name _getCleanedProfileHTML that reflects what the function does.
- #226
=> changed the name of `_getProfilePage` to `_getCleanedProfileHTML`

threads-api/src/threads-api.ts
Loading `dotenv` configurations should be performed by the consumer codebases of the api.
I don't think there is a need to call it here.
Resolves #233
=> fix(api): dotenv config was invoked explicitly

threads-api/package.json
=> api: Move `dotenv` to devDependencies

threads-api/src/threads-api.ts
=> api: Fix verbose logs and `ThreadsAPIError` messages

threads-api/src/threads-api.ts
This was a regression caused by 200ad48d33dc8afe6d14a6e627ac36b1fe711820
=> fix: align the `publish` result with its return type
